version: 2

sphinx:
  builder: html
  configuration: docs/conf.py

formats:
  - htmlzip
  - pdf

python:
  version: 3.8
  install:
    - requirements: requirements.txt
    - requirements: requirements-optional.txt
    - requirements: requirements-dev.txt
