# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            BayesO
description:      'BayesO: A Bayesian optimization framework in Python'
url:              https://bayeso.org
baseurl:          /

author:
  name:           'Jungtaek Kim'
  url:            https://jungtaekkim.github.io

version-bayeso:   0.5.4
version-bench:    0.1.7
version-batch:    0.1.0

github:
  repo-bayeso:    https://github.com/jungtaekkim/bayeso
  repo-bench:     https://github.com/jungtaekkim/bayeso-benchmarks
  repo-batch:     https://github.com/jungtaekkim/batch-bayeso
