# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            BayesO
description:      'Simple, but essential Bayesian optimization package'
url:              https://bayeso.org
baseurl:          /
paginate:         5

author:
  name:           'Jungtaek Kim'
  url:            https://jungtaek.github.io


# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jungtaekkim/bayeso
