# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            BayesO
description:      'Simple, but essential Bayesian optimization package'
url:              https://bayeso.org
baseurl:          /

author:
  name:           'Jungtaek Kim'
  url:            https://jungtaek.github.io


# Custom vars
version:          0.5.3

github:
  repo:           https://github.com/jungtaekkim/bayeso
