# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            BayesO
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://bayeso.org
baseurl:          /
paginate:         5

author:
  name:           'Jungtaek Kim'
  url:            https://twitter.com/mdo


# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jungtaekkim/bayeso
