# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            BayesO
description:      'BayesO: A Bayesian optimization framework in Python'
url:              https://bayeso.org
baseurl:          /
documentation:    https://bayeso.readthedocs.io/en/main/

author:
  name:           'Jungtaek Kim'
  url:            https://jungtaek.github.io


# Custom vars
version:          0.5.3

github:
  repo-bayeso:    https://github.com/jungtaekkim/bayeso
  repo-bench:     https://github.com/jungtaekkim/bayeso-benchmarks
  repo-batch:     https://github.com/jungtaekkim/batch-bayeso
